$schema: 'http://json.schemastore.org/buildkite'
steps:
  - label: ':docker:'
    command: .buildkite/validate-docker-compose.sh
    agents:
      queue: 'baremetal'
  - label: ':lipstick:'
    command: .buildkite/prettier-check.sh
    agents:
      queue: 'baremetal'
  - label: ':rice:'
    command: .buildkite/test-pure-docker.sh
    agents:
      queue: 'baremetal'
